/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pedometer.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class StepInfo {
  
  @SerializedName("Id")
  private Integer id = null;
  @SerializedName("UserId")
  private String userId = null;
  @SerializedName("TimeStamp")
  private Long timeStamp = null;
  @SerializedName("TodaySteps")
  private Integer todaySteps = null;
  @SerializedName("Distance")
  private Float distance = null;
  @SerializedName("Calories")
  private Float calories = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTimeStamp() {
    return timeStamp;
  }
  public void setTimeStamp(Long timeStamp) {
    this.timeStamp = timeStamp;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTodaySteps() {
    return todaySteps;
  }
  public void setTodaySteps(Integer todaySteps) {
    this.todaySteps = todaySteps;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getDistance() {
    return distance;
  }
  public void setDistance(Float distance) {
    this.distance = distance;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getCalories() {
    return calories;
  }
  public void setCalories(Float calories) {
    this.calories = calories;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StepInfo stepInfo = (StepInfo) o;
    return (this.id == null ? stepInfo.id == null : this.id.equals(stepInfo.id)) &&
        (this.userId == null ? stepInfo.userId == null : this.userId.equals(stepInfo.userId)) &&
        (this.timeStamp == null ? stepInfo.timeStamp == null : this.timeStamp.equals(stepInfo.timeStamp)) &&
        (this.todaySteps == null ? stepInfo.todaySteps == null : this.todaySteps.equals(stepInfo.todaySteps)) &&
        (this.distance == null ? stepInfo.distance == null : this.distance.equals(stepInfo.distance)) &&
        (this.calories == null ? stepInfo.calories == null : this.calories.equals(stepInfo.calories));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.timeStamp == null ? 0: this.timeStamp.hashCode());
    result = 31 * result + (this.todaySteps == null ? 0: this.todaySteps.hashCode());
    result = 31 * result + (this.distance == null ? 0: this.distance.hashCode());
    result = 31 * result + (this.calories == null ? 0: this.calories.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepInfo {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  timeStamp: ").append(timeStamp).append("\n");
    sb.append("  todaySteps: ").append(todaySteps).append("\n");
    sb.append("  distance: ").append(distance).append("\n");
    sb.append("  calories: ").append(calories).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
