/**
 * WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: v1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pedometer.client.model;

import io.swagger.annotations.*;

import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserInfo {

    @SerializedName("Id")
    private String id = null;
    @SerializedName("UserName")
    private String userName = null;
    @SerializedName("Password")
    private String password = null;
    @SerializedName("Phone")
    private String phone = null;
    @SerializedName("Height")
    private Float height = null;
    @SerializedName("Weight")
    private Float weight = null;
    @SerializedName("DeviceToken")
    private String deviceToken = null;

    public UserInfo() {
    }

    public UserInfo(String id, String password, String deviceToken) {
        this.id = id;
        this.password = password;
        this.deviceToken = deviceToken;
    }

    public UserInfo(String id, String userName, String password, String phone, Float height, Float weight, String deviceToken) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.phone = phone;
        this.height = height;
        this.weight = weight;
        this.deviceToken = deviceToken;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Float getHeight() {
        return height;
    }

    public void setHeight(Float height) {
        this.height = height;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Float getWeight() {
        return weight;
    }

    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDeviceToken() {
        return deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserInfo userInfo = (UserInfo) o;
        return (this.id == null ? userInfo.id == null : this.id.equals(userInfo.id)) &&
                (this.userName == null ? userInfo.userName == null : this.userName.equals(userInfo.userName)) &&
                (this.password == null ? userInfo.password == null : this.password.equals(userInfo.password)) &&
                (this.phone == null ? userInfo.phone == null : this.phone.equals(userInfo.phone)) &&
                (this.height == null ? userInfo.height == null : this.height.equals(userInfo.height)) &&
                (this.weight == null ? userInfo.weight == null : this.weight.equals(userInfo.weight)) &&
                (this.deviceToken == null ? userInfo.deviceToken == null : this.deviceToken.equals(userInfo.deviceToken));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
        result = 31 * result + (this.userName == null ? 0 : this.userName.hashCode());
        result = 31 * result + (this.password == null ? 0 : this.password.hashCode());
        result = 31 * result + (this.phone == null ? 0 : this.phone.hashCode());
        result = 31 * result + (this.height == null ? 0 : this.height.hashCode());
        result = 31 * result + (this.weight == null ? 0 : this.weight.hashCode());
        result = 31 * result + (this.deviceToken == null ? 0 : this.deviceToken.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserInfo {\n");

        sb.append("  id: ").append(id).append("\n");
        sb.append("  userName: ").append(userName).append("\n");
        sb.append("  password: ").append(password).append("\n");
        sb.append("  phone: ").append(phone).append("\n");
        sb.append("  height: ").append(height).append("\n");
        sb.append("  weight: ").append(weight).append("\n");
        sb.append("  deviceToken: ").append(deviceToken).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
